from flask import Flask
from dash import Dash

server = Flask('myproject')
app = Dash(server=server)
app.scripts.config.serve_locally = True
# Some ids are generated by callbacks, and are not in the initial layout, so they throw errors
app.config['suppress_callback_exceptions'] = True
